name: tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: # Supports manual triggering

env:
  # increment to "clear" the cache
  CACHE_VERSION: "v1"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.2
        with:
          cli: 1.12.0.1530
          lein: 2.11.2
          bb: latest

      - name: Cache clojure dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          key: cljdeps-${{ env.CACHE_VERSION }}-${{ hashFiles('project.clj') }}-${{ hashFiles('deps.edn') }}-${{ hashFiles('bb.edn') }}
          restore-keys: cljdeps-${{ env.CACHE_VERSION }}-

      - name: Prepare dotnet
        uses: xt0rted/setup-dotnet@v1.5.0

      - name: Install ClojureCLR
        run: |
          dotnet tool install --global Clojure.Main --version 1.12.2
          dotnet tool install --global Clojure.Cljr --version 0.1.0-alpha6

      - name: Prepare node
        uses: actions/setup-node@v4
        with:
          node-version: "23.x"
          check-latest: true
          cache: 'npm'
          cache-dependency-path: "package-lock.json"

      - name: Install Node Dependencies
        run: npm ci

      - name: Compile ClojureScript Tests
        run: npm run build

      - name: Run ClojureScript Tests
        run: npm test

      - name: Run Clojure tests
        run: lein test

      - name: Run ClojureCLR Tests
        run: cljr -X:test

      - name: Run babashka tests
        run: bb test-bb
